### ISSUE TITLE
More than one grid at presenter

### ISSUE THREAD

**Issue by ZbyRih** [uestla/TwiGrid#37] opened 2018-01-11 23:15 UTC
fix

```php

	protected function attached($presenter){
		if($presenter instanceof NPresenter){
			$this->build();
			parent::attached($presenter);
			$this->session = $presenter->getSession(__CLASS__ . '-' . $this->getName());

			if(!isset($presenter->payload->twiGrid)){
				$this->payload = $presenter->payload->twiGrid = new \stdClass();
				$this->payload->forms = [];
			}else{
				$this->payload = $presenter->payload->twiGrid; // this is fix
			}
		}
	}

```

**Comment by GEp1c** [comment] 2019-06-12 13:30
Duplicate of #35 ... can we fix this already @uestla ? It's important for me as well

**Comment by ZbyRih** [comment] 2019-06-12 13:37
this is dead, use contributte/datagrid instead

**Comment by GEp1c** [comment] 2019-06-12 13:42
@ZbyRih I don't want to use contributte/datagrid, TwiGrid is much easier to work with. I'm using TwiGrid for a very long time (3 years +-) and it works like a charm, this is the only problem with it.

**Comment by ZbyRih** [comment] 2019-06-13 03:03
@GEp1c i understand, i have same thoughts, however when its not maintain anymore, and i had to write lots of feature into, which contribute/datagrid has in basic

**Comment by uestla** [comment] 2019-07-05 17:54
Duplication of https://github.com/uestla/TwiGrid/issues/35

Will resolve in that thread - closing this.

**Closed by uestla** 2019-07-05 17:54 UTC
